[tool.poetry]
name = "snapjaw"
version = "1.0"
description = "Vanilla WoW AddOn Manager"
authors = ["Roman Kharitonov <rkharito@yandex.ru>"]
license = "GPL-3.0-or-later"

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
GitPython = "^3.1.27"
tabulate = "^0.8.10"
colorama = "^0.4.5"
dataclasses-json = "^0.5.7"
humanize = "^4.4.0"
checksumdir = "^1.2.0"

[tool.poetry.group.dev.dependencies]
pyinstaller = "^5.10.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
