name: Package

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: '0 0 * * 0'

jobs:
  package:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: x64

      - name: Cache Python packages
        uses: actions/cache@v3
        with:
          path: |
            ~\AppData\Local\pip\Cache
            ~\AppData\Local\pypoetry
          key: python-deps

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade poetry
          poetry install --sync --no-root

      - name: Cache Nuitka
        uses: actions/cache@v3
        with:
          path: |
            ~\AppData\Local\Nuitka
          key: nuitka

      - name: Build
        run: |
          poetry run nuitka --standalone --prefer-source-code --mingw64 --assume-yes-for-downloads --show-scons --output-dir=build --include-module=_cffi_backend src\snapjaw.py
          New-Item -ItemType directory -Name snapjaw\snapjaw -Path build
          Get-Item -Path build\snapjaw.dist\* | Move-Item -Destination build\snapjaw\snapjaw

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: snapjaw
          path: build\snapjaw\
