name: Package

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade poetry
          poetry install --no-root

      - name: Build
        run:
          poetry run nuitka --onefile --standalone --prefer-source-code --assume-yes-for-downloads --show-scons --output-dir=build --remove-output --include-module=_cffi_backend src/snapjaw.py

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: snapjaw
          path: build/snapjaw.exe
