name: Package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Prepare dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade poetry
          poetry export --format requirements.txt >src/requirements.txt

      - name: Build
        uses: JackMcKew/pyinstaller-action-windows@python3-10-pyinstaller-5-3
        with:
          path: src

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: snapjaw
          path: src/dist/windows
